beer_collection/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_app.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]

main_app/urls.py
from django.urls import path
from . import views
from django.contrib.staticfiles.storage import staticfiles_storage
from django.views.generic.base import RedirectView

urlpatterns = [
    path('', views.home, name='home'),
    path('about/', views.about, name='about'),
    path('beers/', views.beers_index, name='index'),
    path('beers/<int:beer_id>/add_drinking', views.add_drinking, name='add_drinking'),
    # adds photo
    path('beers/<int:beer_id>/add_photo', views.add_photo, name='add_photo'),
    path('beers/<int:beer_id>/', views.beers_detail, name='detail'),
    path('beers/create/', views.BeerCreate.as_view(), name='beers_create'),
    path('beers/<int:pk>/update/', views.BeerUpdate.as_view(), name='beers_update'),
    path('beers/<int:pk>/delete/', views.BeerDelete.as_view(), name='beers_delete'),
    path('beers/<int:beer_id>/assoc_hop/<int:hop_id>/', views.assoc_hop, name='assoc_hop'),
    path('hops/', views.hops_index, name='hops_index'),
    path('hops/<int:hop_id>/', views.hops_detail, name='hops_detail'),
    path('hops/create/', views.HopsCreate.as_view(), name='hops_create'),
    path('hops/<int:pk>/update/', views.HopsUpdate.as_view(), name='hops_update'),
    path('hops/<int:pk>/delete/', views.HopsDelete.as_view(), name='hops_delete'),
    path('venues/', views.venues_index, name='venues_index'),
    path('venues/<int:venue_id>/', views.venue_detail, name='venues_detail'),
    path('venues/create', views.VenueCreate.as_view(), name='venues_create'),
    path('venues/<int:pk>/update/', views.VenueUpdate.as_view(), name='venue_update'),
    path('venues/<int:pk>/delete/', views.VenueDelete.as_view(), name='venue_delete'),
    path('beers/<int:beer_id>/assoc_venue/<int:venue_id>/', views.assoc_venue, name='assoc_venue'),
    #attempting a favicon
    path('favicon.ico', RedirectView.as_view(url=staticfiles_storage.url('img/favicon.ico'))),
    # sign up
    path('accounts/signup/', views.signup, name='signup'),
    

]

main_app/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User

# Create your models here.

SERVED = (
    ('C', 'Can'),
    ('B', 'Bottle'),
    ('D', 'Draft'),
    ('G', 'Growler'),
)

class Venue(models.Model):
    name = models.CharField(max_length=25, default='')
    address = models.CharField(max_length=45, default='')
    city = models.CharField(max_length=30, default='')
    state = models.CharField(max_length=15, default='')

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('detail', kwargs={'venue_id': self.id})



class Hop(models.Model):
    name = models.CharField(max_length=15, default='')
    characteristics = models.CharField(max_length=170, default='')
    alpha_acid = models.DecimalField(max_digits=5, decimal_places=2, default='')

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('detail', kwargs={'hop_id': self.id})



class Beer(models.Model):
    brewery_name = models.CharField(max_length=100)
    beer_name = models.CharField(max_length=100)
    description = models.TextField(max_length=250)
    type = models.CharField(max_length=15)
    abv = models.DecimalField(max_digits=5, decimal_places=2)
    # add M:M relationship
    hops = models.ManyToManyField(Hop)
    venues = models.ManyToManyField(Venue)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return(self.beer_name)
  
    def get_absolute_url(self):
        return reverse('detail', kwargs={'beer_id': self.id})


class Photo(models.Model):
    url = models.CharField(max_length=200)
    beer = models.ForeignKey(Beer, on_delete=models.CASCADE)

    def __str__(self):
        return f"Photo for beer_id: {self.beer_id} @{self.url}"

class Drinking(models.Model):
    class Meta:
        ordering = ['-date']
    
    date = models.DateField('drinking date')
    served = models.CharField(
        max_length=1,
        choices=SERVED,
        default=SERVED[0][0]
    )

    beer = models.ForeignKey(Beer, on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.get_served_display()} on {self.date}"

main_app/forms.py
from django.forms import ModelForm
from .models import Drinking

class DrinkingForm(ModelForm):
    class Meta:
        model = Drinking
        fields = ['date', 'served']

main_app/views.py
from django.contrib.auth.models import User
from django.views.generic.edit import CreateView, DeleteView, UpdateView
from django.shortcuts import redirect, render
from django.contrib.auth import login
from .models import Beer, Hop, Venue, Photo
from .forms import DrinkingForm
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.decorators import login_required # for def
from django.contrib.auth.mixins import LoginRequiredMixin # for class

import boto3
import uuid

S3_BASE_URL = 'http://s3.us-east-1.amazonaws.com/'
BUCKET = 'nils-beer-collector'

# Create your views here.
def home(request):
    return render(request, 'home.html')

def about(request):
    return render(request, 'about.html')

def signup(request):
    error_message = ''
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect('index')
        else:
            error_message = 'Invalid Signup Data - Please try again'

    form = UserCreationForm()
    return render(request, 'registration/signup.html', {'form': form, 'error_message': error_message })

@login_required
def beers_index(request):
    beers = Beer.objects.filter(user=request.user).order_by('abv')
    return render(request, 'beers/index.html', {'beers': beers})

@login_required
def add_drinking(request, beer_id):
    form = DrinkingForm(request.POST)
    if form.is_valid():
        new_drinking = form.save(commit=False)
        new_drinking.beer_id = beer_id
        new_drinking.save()
    return redirect('detail', beer_id=beer_id)

@login_required
def add_photo(request, beer_id):
    photo_file = request.FILES.get('photo-file', None)
    if photo_file:
        s3 = boto3.client('s3')
        key = uuid.uuid4().hex[:6] + photo_file.name[photo_file.name.rfind('.'):]
        try:
            s3.upload_fileobj(photo_file, BUCKET, key)
            url = f"{S3_BASE_URL}{BUCKET}/{key}"
            photo = Photo(url=url, beer_id=beer_id)
            photo.save()
        except Exception as error:
            print('An error occured uploading file to S3')
            print(error)
    return redirect('detail', beer_id=beer_id)            

@login_required
def beers_detail(request, beer_id):
    beer = Beer.objects.get(id=beer_id)
    hops_beer_doesnt_have = Hop.objects.exclude(id__in = beer.hops.all().values_list('id'))
    venue_beer_doesnt_have = Venue.objects.exclude(id__in = beer.venues.all().values_list('id'))
    drinking_form = DrinkingForm()
    return render(request, 'beers/detail.html', {
        'beer': beer,
        'drinking_form': drinking_form,
        'hops': hops_beer_doesnt_have,
        'venues': venue_beer_doesnt_have,
        })

# def assoc_hop(request, beer_id, hop_id):
#     Beer.objects.get(id=beer_id).hops.add(hop_id)
#     return redirect('detail', beer_id=beer_id)

@login_required
def assoc_hop(request, beer_id, hop_id):
    Beer.objects.get(id=beer_id).hops.add(hop_id)
    return redirect('detail', beer_id=beer_id)

@login_required
def assoc_venue(request, beer_id, venue_id):
    Beer.objects.get(id=beer_id).venues.add(venue_id)
    return redirect('detail', beer_id=beer_id)

LoginRequiredMixin
class BeerCreate(CreateView):
    model = Beer
    fields = ['brewery_name', 'beer_name', 'description', 'type', 'abv']
    success_url = '/beers/'
    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)

LoginRequiredMixin
class BeerUpdate(UpdateView):
    model = Beer
    fields = ['description', 'type', 'abv']

LoginRequiredMixin
class BeerDelete(DeleteView):
    model = Beer
    success_url = '/beers/'

@login_required
def hops_index(request):
    hops = Hop.objects.all()
    return render(request, 'hops/index.html', {'hops': hops})

@login_required
def hops_detail(request, hop_id):
    hop = Hop.objects.get(id=hop_id)
    return render(request, 'hops/detail.html', {'hop': hop})

LoginRequiredMixin
class HopsCreate(CreateView):
    model = Hop
    fields = '__all__'
    success_url = '/hops/'

LoginRequiredMixin
class HopsUpdate(UpdateView):
    model = Hop
    fields = ['characteristics', 'alpha_acid']

LoginRequiredMixin
class HopsDelete(DeleteView):
    model = Hop
    success_url = '/hops/'

@login_required
def venues_index(request):
    venue = Venue.objects.all()
    return render(request, 'venues/index.html', {'venue': venue})

@login_required
def venue_detail(request, venue_id):
    venue = Venue.objects.get(id=venue_id)
    return render(request, 'venues/detail.html', {'venue': venue})

LoginRequiredMixin
class VenueCreate(CreateView):
    model = Venue
    fields = '__all__'
    success_url = '/venues/'

LoginRequiredMixin
class VenueUpdate(UpdateView):
    model = Venue
    fields = ['address', 'city', 'state']
    success_url = '/venues/'

LoginRequiredMixin
class VenueDelete(DeleteView):
    model = Venue
    success_url = '/venues/'

main_app/templates/beers/detail.html
{% extends 'base.html' %}
{% block content %}
    <h1>Beer Details- </h1>
    <div class="row">
        <div class="col s6">
            <div class="card">
                <div class="card-content">
                    <span class="card-title">{{ beer.beer_name }}</span>
                    <p>Brewery: {{ beer.brewery_name }}</p>
                    <p>Description: {{ beer.description }}</p>
                    <p>Type of Beer: {{ beer.type }}</p>
                    <p>ABV: {{ beer.abv }}%</p>
                </div>
                <div class="card-action">
                    <a href="{% url 'beers_update' beer.id %}">Edit</a>
                    <a href="{% url 'beers_delete' beer.id %}">Delete</a>
                </div>
            </div>
            {% for photo in beer.photo_set.all %}
                <img src="{{photo.url}}" alt="{{beer.beer_name}}" class="responsive-img card-panel">
            {% empty %}
                <div class="card-panel teal-text center-align">No Photos Uploaded</div>
            {% endfor %}
            <form class="card-panel" action="{% url 'add_photo' beer.id %}" method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                <input type="file" name="photo-file">
                <br>
                <br>
                <input type="submit" class="btn" value="Upload Photo">
            </form>
        </div>
        <div class="col s6">
            <form action="{% url 'add_drinking' beer.id %}" method="POST">
                {% csrf_token %}
                {{ drinking_form.as_p }}
                <input type="submit" class="btn" value="Add Date Drank">
            </form>
            <table class="striped">
                <thead>
                    <tr>
                        <th>Date Drank:</th>
                        <th>Served:</th>
                    </tr>
                </thead>
                <tbody>
                    {% for drinking in beer.drinking_set.all %}
                    <tr>
                        <td>{{ drinking.date }}</td>
                        <td>{{ drinking.get_served_display }}</td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
<!-- markup for hops -->

    <hr>
    <div class="row">
        <div class="col s6">
            <h3>{{ beer.beer_name }}'s Hops</h3>
        {% if beer.hops.count %}
            {% for hop in beer.hops.all %}
                <div class="card">
                    <div class="card-content">
                        <span class="card-title">
                            A {{ hop.name }}
                        </span>
                    </div>
                </div>
            {% endfor %}
        {% else %}
            <h5>No Hops</h5>
        {% endif %}
        </div>
    
        <div class="col s6">
            <h3>Available Hops</h3>
        {% if hops.count %}
            {% for hop in hops.all %}
                <div class="card">
                    <div class="card-content">
                        <span class="card-title">
                            A {{ hop.name }}
                        </span>
                    </div>
                    <div class="card-action">
                        <form action="{% url 'assoc_hop' beer.id hop.id %}" method="POST">
                            {% csrf_token %}
                            <button type="submit" class="btn">Add Hop</button>
                        </form>
                    </div>
                </div>
            {% endfor %}
        {% else %} 
            <h5>{{ beer.beer_name }} already has all available hops</h5>
        {% endif %}
        </div>

    </div>
   <!-- markup for venues -->
        <hr>
<div class="row">
    <div class="col s6">
        <h3>{{ beer.beer_name }}'s Consumption Location</h3>
    {% if beer.venues.count %}
        {% for venue in beer.venues.all %}
            <div class="card">
                <div class="card-content">
                    <span class="card-title">
                        {{ venue.name }}
                    </span>
                </div>
            </div>
        {% endfor %}
    {% else %}
        <h5>No Venues</h5>
    {% endif %}
    </div>

    <div class="col s6">
        <h3>Available Venues</h3>
        {% if venues.count %}
            {% for venue in venues.all %}
                <div class="card">
                    <div class="card-content">
                        <span class="card-title">
                            {{ venue.name }}
                        </span>
                    </div>
                    <div class="card-action">
                        <form action="{% url 'assoc_venue' beer.id venue.id %}" method="POST">
                            {% csrf_token %}
                            <button type="submit" class="btn">Add</button>
                        </form>
                    </div>
                </div>
            {% endfor %}
        {% else %}
            <h5>{{ beer.beer_name }} already has been consumed at all available venues.</h5>
        {% endif %}
    </div>
</div>
    </div>

    <script>
        // Constants
        const dateEl = document.getElementById('id_date');
        const selectEl = document.getElementById('id_served');

        // Configure datepicker
        M.Datepicker.init(dateEl, {
            format: 'yyyy-mm-dd',
            default: new Date(),
            setDefault: true,
            autoClose: true,
        });

        // Configure the select tag
        M.FormSelect.init(selectEl);
        
    </script>

{% endblock %}

main_app/templates/beers/index.html
{% extends 'base.html' %}
{% block content %}
    <h1>Beer List</h1>
    {% for beer in beers %}
        <div class="card">
            <a href="{% url 'detail' beer.id %}">
                <div class="card-content">
                    <span class="card-title">{{ beer.beer_name }}</span>
                    <p>Brewery: {{ beer.brewery_name }}</p>
                    <p>Description: {{ beer.description }}</p>
                    <p>Type of Beer: {{ beer.type }}</p>
                    <p>ABV: {{ beer.abv }}%</p>

                </div>
            </a>
        </div>
    {% endfor %}
{% endblock %}